### ISSUE TITLE
Modify D format

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#157] opened 2016-11-14 18:24 UTC
Currently the disparity D is written with three channels, x, y, and mask. It will save on storage to simply use a no-data value in the GeoHeader for the 3rd channel, such as the smallest int32.

**Comment by ScottMcMichael** [comment] 2018-06-07 03:29
Duplicate of issue #121

**Closed by ScottMcMichael** 2018-06-07 03:29 UTC
