### ISSUE TITLE
About the ASP conda environment and ISIS conda environment variable ISISROOT.

### ISSUE THREAD

**Issue by whigg** [NeoGeographyToolkit/StereoPipeline#378] opened 2022-08-09 13:03 UTC
Hi,

I create an environment for asp and isis with conda seperately, but I am confused about the environment variable ISISROOT.

According to the ISIS installation instructions, set the ISISROOT environment variable:
export ISISROOT=$HOME/anaconda3/envs/isis

According to the ASP installation instructions, set the ISISROOT environment variable:

export ISISROOT=$HOME/anaconda3/envs/asp

So, How exactly set the ISISROOT environment variables for these two virtual environments?

Thanks.

**Comment by rbeyer** [comment] 2022-08-09 14:37
@whigg, this appears to be a duplicate of [Discussion 377](https://github.com/NeoGeographyToolkit/StereoPipeline/discussions/377), and is indeed a question, and not an Issue with the software or code, so I'm closing this Issue as a duplicate.

**Closed by rbeyer** 2022-08-09 14:37 UTC
